// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deleteChirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChirpByUserID = `-- name: DeleteChirpByUserID :one
DELETE FROM chirps
WHERE 
    id = $1
    AND user_id = $2
RETURNING id
`

type DeleteChirpByUserIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteChirpByUserID(ctx context.Context, arg DeleteChirpByUserIDParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteChirpByUserID, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
