// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: upgradeToRed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upgradeUserToChirpyRed = `-- name: UpgradeUserToChirpyRed :one
UPDATE users
SET is_chirpy_red = true
WHERE id = $1
RETURNING id
`

func (q *Queries) UpgradeUserToChirpyRed(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, upgradeUserToChirpyRed, id)
	err := row.Scan(&id)
	return id, err
}
